services:
  oficina-app:
    profiles:
      - prod
    image: ${REGISTRY:-grecomilani}/oficina-app:${TAG:-latest}
    build: null
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DDL_AUTO: validate
      SQL_INIT_MODE: never
      SHOW_SQL: false
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
