spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/oficina-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:false}

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

logging:
  level:
    root: INFO
