apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina-local
resources:
  - ../../base
  - namespace.yaml
images:
  - name: fiapsoatgrupo36/product-service
    newName: oficina/product-service
    newTag: local
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
