apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8083"
  EUREKA_URL: "http://eureka-service:8761/eureka/"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: ""
